AllCops:
  TargetRubyVersion: 2.3

Metrics/LineLength:
  Max: 120

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/ClassVars:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
